name: Publish on Netlify

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.43/quarto-1.6.43-linux-amd64.tar.gz
        tar xzf quarto-1.6.43-linux-amd64.tar.gz
    
    - name: render
      run: cd stan-users-guide && ../quarto-1.6.43/bin/quarto render --to html
    
    - name: deploy
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        netlify link --name stan-cn
