name: Publish on Netlify

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: quarto-setup
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.43
      
      - name: quarto-render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: stan-users-guide
      
      - name: netlify-link
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: link --name stan-cn
      
      - name: netlify-deploy
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: deploy --dir=stan-users-guide/_book --prod
